/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define GIT_COMMIT_CNT -5073

#define GIT_COMMIT_DATE 2023-06-22 09:47:27

#define GIT_SHA 16e70e28584c

#define HAVE_ALSA 0

#define HAVE_BACKTRACE 1

#define HAVE_ICONV 1

#define HAVE_KLOGCTL 1

#define HAVE_LIBUDEV 1

#define HAVE_QTGL 0

#define HAVE_SECURE_GETENV 1

#define HAVE_STRERRORNAME_NP 1

#define HAVE_SYS_KLOG_H 1

#define HAVE_VISIBILITY 1

#define ICONV_CONST 

#define LOCALEDIR "/usr/local/share/locale"

#define MAJOR 1

#define MINOR 25

#define PACKAGE "v4l-utils"

#define PACKAGE_VERSION "1.25.0"

#define PATCH 0

#define V4L_UTILS_VERSION "1.25.0"

